version: "3.2"
services:
   
  postgres:
    image: postgres
    restart: always
    container_name: "bb-hack2k22"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
